### ISSUE TITLE
ov7670

### ISSUE THREAD

**Issue by mashiro17** [electro-logic/ASF-components#1]
Hi, I'm working with an ov7670 and a Atxmega256a3u; could you please upload the libraries?

**Comment by electro-logic** [comment]
Ciao Mashiro, pubblicherò prossimamente le librerie, che progetto stai realizzando?

**Comment by mashiro17** [comment]
Ciao, stiamo realizzando una scheda basata su un xmega256a3u con un at86rf212b e nelle intenzioni c'era di realizzare qualcosa di simile al tuo progetto di trasferire via wireless le immagini con una rete subghz e in un secondo tempo con uno schermo tft. Ho trovato un pò di difficoltà nell'interfacciarmi con la telecamera perché non ho trovato una documentazione adeguata e quindi speravo di trovare aiuto nelle tue librerie.

**Comment by electro-logic** [comment]
Ciao Mashiro,

Le librerie non sono state sviluppate per applicazioni del genere anche se naturalmente è possibile utilizzarle a proprio piacimento. Ho realizzato progetti abbastanza diversi da quello che hai dedotto.

Le prestazioni con xmega e ricetrasmettitori a banda così stretta però non saranno molto accattivanti.. 

Con qualche calcolo sulla banda, memoria e prestazioni del micro puoi farti rapidamente un'idea di che risoluzione e frame-rate potrai raggiungere. Lo schermo TFT porterà via ulteriori risorse di calcolo e peggiorerà ulteriormente il frame-rate.

Hai preso in considerazione l'utilizzo di un ARM ad alte prestazioni e di una trasmissione wireless a banda più elevata come ad esempio WiFi? Anche un sensore cmos con compressione JPEG integrata ridurrebbe molto i requisiti di banda.

Omnivision è orientata ai grandi clienti con cui spesso sviluppa in sinergia i progetti, con le loro dev-board ufficiali viene fornito un tool per tarare i registri interni dei sensori cmos.

Nella libreria non troverai documentazione adeguata, che puoi però richiedere ad Omnivision contattando un commerciale.

**Comment by mashiro17** [comment]
Ciao, 
da qualche parte avevo letto,forse sul blog o su un forum, che le immagini raccolte dalla telecamera le trasferivi tramite una scheda wireless a 2,4 ghz su un pc. 
Più o meno l'idea era quella solo che lavorando in 868mhz.
Poi come alternativa al pc ho pensato in un secondo tempo a un tft tipo l'ili9341, immaginavo che mettere sullo stesso micro: telecamera e lcd sarebbe stato chiedere troppo.
La scheda ha comunque sia il pinout per la seriale che quello per l'usb per cui inizialmente mi andrebbe bene anche solo collegare la telecamera e tirare via i dati da seriale su pc il trasferimento radio è secondario.
Al momento però mi sono fermato alle intenzioni: ho provato a collegare la telecamera e a parlarci via i2c come indicato su alcuni esempi e anche nella documentazione ma non ho cavato un ragno dal buco. Per questo ero alla ricerca di qualche spunto per xmega che potesse essere una base di partenza.
Ti ringrazio per i consigli in ogni caso.

**Comment by electro-logic** [comment]
Ciao,

Il progetto non era però fondato sullo streaming di flussi video ne loro visualizzazione su TFT, le immagini venivano spedite a bassa risoluzione e con frame-rate molto bassi per il solo puntamento, molto lontano da un flusso video come può essere un film.

Con USB 2.0 Full-Speed sei comunque molto vincolato in termini di banda, cosa vuoi ottenere come risultato finale?

Una buona alternativa per prestazioni migliori può essere una raspberry con webcam ed una chiavetta wifi.

Sono abbastanza impegnato in questo periodo e non riesco a pubblicare la libreria a breve. Quando sarà pubblicata pubblicherò un messaggio in questa discussione così potrai avere una notifica per email.

Ad ogni modo ti ringrazio per aver visitato il mio blog
Leonardo

**Comment by mashiro17** [comment]
Va benissimo una cosa che faccia il solo puntamento :)
Grazie per i consigli!
Giulio aka mashiro

**Comment by electro-logic** [comment]
Ciao Giulio,

Per curiosità, hai una applicazione finale oppure stai solamente sperimentando con l'elettronica?

**Comment by mashiro17** [comment]
Ciao Leonardo,
Sto lavorando alle librerie per una nuova scheda di prossima uscita.
Il codice specifico della telecamera potrebbe servirci per alcuni progetti di domotica integrando i sensori con la telecamera in un sistema più complesso con altri sensori o magari telecamere più potenti.
